language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
before_deploy:
- pip install --user release-manager==0.3.0
deploy:
  skip_cleanup: true
  provider: script
  script: release-manager --config ./.travis/release.yml --check-version --make-version --make-artifact --upload-artifact
  on:
    tags: true
env:
  global:
  - secure: FpFfqcuDuxasw+P+fj62m/NRFWj9Dov74R/6KjdVVn4YdL1PTsqLc6sqttbcJsbobWX9B70LwKKhlYxyL1fWTx6zUe2owXAxtR0Bw2y0WNT6D4XKtfmJYWcVOSGjKJciURaTS9Hi4vypMp06buul+BguuerxW430I6Oo3xMNZF6MDgEJoS6NPL+rzg4l8aqgq+v9PF56ABcyvpHvLwKURz2FvyVE0rj3IJdetZsme/zRkqy+TXA8kGgX2ABgQxohI3kMgJ0sRxhDPN49Ziqjovwmxdg/DkXQJRRzbY5auI/sL0eOhU0ECEDzpfrQEoDBvfuapPEfd3CGfxgH/puXIs8cOQ4gH4NovUQVwdPkpSq/wCEM1j+w4ueSY4+XHRNTKwMYC9oe+YFFCqmAkF2gysYliMV/75ZXa4MMTiCWmKQZZHuSvFRz+tmIv9v1ey2EFc89LeihlxyaUVPsMRhNCg9NOlQ1VcXjaDFqW7Q0udPCIh/32tsoXtkMd7ZriYvG+KIJDZeRf3coYQ9n6SEhfpkizzT/rHcCCnV3iCuA4h2kUYmQkvztRzYGGdttpcOU4Y36teyXnwDv/cZ9FapPSiroydgj/08jcrgkvonzm2me4ddxR/38LmlrbcG2Q/7AhUj2cgICGLjys1OcjvrvZVsINF2u1kJ3qfH5ng6f2X8=
  - secure: iaLlq1SC9zkAr5GJXCFi7bwhGs0PwkMv4ntehYZOM4HS+jA/uAfTZcVHAEHoCvkKSUpM0o4jZA5hJZM8xeYKl7aheePmFscDgJUSqcrgXlAzzBgrxn54CDy/ezmZfV2BM86e8kiJaWLSu+Znqr0gOjNtbUl5IUPImhGhhDMwyQYI/lXu3RI4kquAtbbwDPpNUR+1HQq1TLTBrq2meQifLah2nK6kAigu+c4P1ESDnciz8h/xTG8tN+z3pX5T2i+VZ5Qb0BChTxC2NPDGXg6ia5rzEmPO963xiIQdvDrXgBBy2uEmXQzS7AgERiGPtsiE/tlh9G2uJedGEdI2b6jJ0L7UFFj39F4vch28j6HUBfm/CVTzCiRWJq2kSp8exboDntP7kqi6pjClahIbvyUsLelkpmVWmj8E50qWK2e+5HZG5Saosuau3r1giRyJN8zkv/0taliTfZWZWKKLdWzb3EdP3sDrCE7ZIYMOCPqgzdviJ/U5AMrcN7QKmbD5C/wpL3ixrwBr16bYglgzrVrIAX973mYvKaIjlgYtNKGckGFyekRgfR0aOnKzVn3nBCg4ssLeMFJW1COHu8EdwGgiIJ7T62oVehqSA6QYeDFNi0UDtegSUpngLLQRhAJ8tgS2BGJNdZgC5A286GY/59vb9NjoTIvsYJ8FBRC+G3qc180=
