name: build

on:
  push:
    branches: [ snyk ]

jobs:

  deploy_docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - streamloader
          - mutator
          - repeater
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get current version
        id: ver
        run: |
          export PROJECT_VERSION=$(sbt "project common" version -Dsbt.log.noformat=true | perl -ne 'print "$1\n" if /info.*(\d+\.\d+\.\d+[^\r\n]*)/' | tail -n 1 | tr -d '\n')
          echo "::set-output name=project_version::$PROJECT_VERSION"


      - name: Build local distroless image, which is needed to run Snyk
        if: true
        run: sbt "project ${{ matrix.app }}Distroless" docker:publishLocal
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        if: true
        with:
          image: "snowplow/snowplow-bigquery-${{ matrix.app }}:${{ github.ref_name }}-distroless"
          args: "--app-vulns --org=data-processing-new"
          command: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
