name: build

on:
  push:
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Publish to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: $GITHUB_WORKSPACE/.github/workflows/deploy.sh ${GITHUB_REF##*/}
      - name: Build artefacts
        run: |
          sbt clean 'project mutator' assembly
          sbt clean 'project repeater' assembly
          sbt clean 'project streamloader' assembly
      - name: Create GitHub release & Attach artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          name: Version ${GITHUB_REF##*/}
          tag_name: ${GITHUB_REF##*/}
          fail_on_unmatched_files: true
          files: |
            mutator/target/scala-2.13/snowplow-bigquery-mutator-${GITHUB_REF##*/}.jar
            repeater/target/scala-2.13/snowplow-bigquery-repeater-${GITHUB_REF##*/}.jar
            streamloader/target/scala-2.13/snowplow-bigquery-streamloader-${GITHUB_REF##*/}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
